version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongo_data:
